### ISSUE TITLE
Enable extended messaging

### ISSUE THREAD

**Issue by birdy247** [SamyCookie/python-ant#11]
Hi

Does this lib provide support to enable extended messaging?  I have been using the windows c++ lib and configure the sitck to use extended messages.  It is in section 7.1.1 in the ANT message protocol

[D00000652_ANT_Message_Protocol_and_Usage_Rev_5.1 (6).pdf](https://github.com/SamyCookie/python-ant/files/241306/D00000652_ANT_Message_Protocol_and_Usage_Rev_5.1.6.pdf)

Thanks

**Comment by SamyCookie** [comment]
Hi,

If it does not working, yes it should be. But I am not the original developper of this tool, and it is out of my personal scope. If someone is willing to implement this functionnality, PRs for review are welcomed here.

Good luck !

**Comment by SamyCookie** [comment]
@bertpig seems to have implemented this. You should ask him if its implementation works well.

see https://github.com/bertpig/python-ant

**Comment by SamyCookie** [comment]
Here too https://github.com/jovial/python-ant
