### ISSUE TITLE
Python3 - TypeError

### ISSUE THREAD

**Issue by half2me** [SamyCookie/python-ant#14]
I have the following code-snippet which runs perfectly fine on python2.7 but fails with an error on python3

``` python
network = node.Network(NETKEY, 'N:ANT+')
antnode.setNetworkKey(0, network)
```

Traceback (most recent call last):
  File "...", line ..., in <module>
    antnode.setNetworkKey(0, network)
  File ".../ant/core/node.py", line 237, in setNetworkKey
  File ".../ant/core/message.py", line 48, in **call**
  File ".../ant/core/message.py", line 294, in **init**
  File ".../ant/core/message.py", line 308, in key
TypeError: can assign only bytes, buffers, or iterables of ints in range(0, 256)

**Comment by SamyCookie** [comment]
could you send me
`print(network.key, type(network.key))`
?

**Comment by half2me** [comment]
Python3 : `¹¥!û½rÃE <class 'str'>`
Python2 : `??!??r?E <type 'str'>`

I'm using the example code `NETKEY = '\xB9\xA5\x21\xFB\xBD\x72\xC3\x45'`

**Comment by SamyCookie** [comment]
Hum, try with a NETKEY as `b'\xB9...'` (not sure)

**Comment by half2me** [comment]
isn't `b'` for binary?

**Comment by SamyCookie** [comment]
yes, it is. But I internally use bytearray object for messages, so a byte string needs to be used.

**Comment by half2me** [comment]
Ah cool :) Everything is working now. Thanks!
