### ISSUE TITLE
Catch USB Exceptions

### ISSUE THREAD

**Issue by half2me** [SamyCookie/python-ant#16]
Is there a way for me to be able to catch USB Exceptions (for example when unplugging the device)
Its on a diff Thread, and I can't really get it in a try-catch loop. :/ Is there some way I can catch this? Some callback to handle exceptions? Like node.registerErrorHandler()?

**Comment by SamyCookie** [comment]
No there is not, but it seems to be a good idea to have one. However I have no time to do it for the moment.
If you can do it, here some inspirations for that
https://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python
https://github.com/SamyCookie/python-ant/blob/dev/src/ant/core/event.py#L178
