### ISSUE TITLE
Dependency issue installing pyusb

### ISSUE THREAD

**Issue by David-Hari** [SamyCookie/python-ant#6]
When I run `python setup.py install`, I get an error about pyusb 1.0.0 not found:

```
Searching for pyusb>=1.0.0
Reading https://pypi.python.org/simple/pyusb/
No local packages or download links found for pyusb>=1.0.0
error: Could not find suitable distribution for Requirement.parse('pyusb>=1.0.0')
```

Apparently, the only registered version is [1.0.0b2](https://pypi.python.org/pypi/pyusb). I had to change this to 'pyusb>=1.0.0b2' to get this to work.

Also (not really related to this project) once I got pyusb 1.0.0b2, I was unable to get it working on Windows. It said it needed a backend installed, but even when I installed libusb it still didn't work.

**Comment by SamyCookie** [comment]
Yes, I confirm that the pyusb version 1.0.0b2 is required.
I personally use this version to make it work ->
https://packages.debian.org/jessie-backports/python-usb
For Windows, I can't help you, sorry :/

**Comment by David-Hari** [comment]
Then can you change the requirement in setup.py to be "pyusb>=1.0.0b2" or "pyusb=1.0.0b2"?
Do you know why greater-than-or-equal doesn't pick up the b2 version?

**Comment by SamyCookie** [comment]
I just did that
5f2bb5d3622d4991b3c338a9669cf6bdb8a164cc.
I don't know why versions have this behaviour.
Thanks for reporting this.
