### ISSUE TITLE
Error when calling ChannelIDMessage.deviceNumber property

### ISSUE THREAD

**Issue by David-Hari** [SamyCookie/python-ant#7]
```
TypeError: 'str' does not support the buffer interface
```

Not sure what it's complaining about, but it sounds like the data type is wrong. Can you have a look?

**Comment by SamyCookie** [comment]
Maybe on monday, can you put the entire stack traceback ?

**Comment by David-Hari** [comment]
That was it, there was no stack trace!
At first I didn't even know how accessing a variable could give such an error, until I realized it was actually a property. Given that, I assume the problem is on this line:

``` python
return unpack(b'<H', str(self._payload[1:3]))[0]
```

Perhaps the payload should not be converted to a string, since it is a bytearray object.

**Comment by SamyCookie** [comment]
Ok I think I got it. It's a Python 3 issue regression because this code works with 2.7. So I assume you are using python3.
2 solutions:
- replace 'str' by 'bytes' and it will works for both versions.
- remove 'str' conversion, and it will  work with you python version

**Comment by David-Hari** [comment]
Well I wonder why anyone is still using Python 2.x, but if you can make it work for both versions then that's good.

**Comment by SamyCookie** [comment]
I use it, for retro compatibility reasons. I think 82f50ff44fcb0b0b505223ff6c2d1bf226195933 fix the issue so I consider the issue closed.
